### ISSUE TITLE
Woocommerce error: Virtual downloadable products aren't usable when Itella module is activated

### ISSUE THREAD

**Issue by rudolfgusta** [ItellaPlugins/itella-shipping-woocommerce#63]
We are having trouble with your module:

Smartpost Itella Shipping
Settings | Deactivate
Smartpost Itella shipping plugin for Woocommerce

Version 1.3.5 | By Itella Team

When adding to the cart a virtual downloadable product, then we get an error in checkout

Failed to accept payment. Please try again.

Server log: 

2022-09-26 08:45:49.712055 [NOTICE] [162979] [172.71.95.8:38242:HTTP2-1#***] [STDERR] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /home/***/public_html/wp-content/plugins/itella-shipping/admin/class-itella-shipping-method.php:1258
Stack trace:
#0 /home/***/public_html/wp-content/plugins/itella-shipping/admin/class-itella-shipping-method.php(1258): in_array()
#1 /home/***/public_html/wp-includes/class-wp-hook.php(309): Itella_Shipping_Method->validate_pickup_point()
#2 /home/***/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#3 /home/***/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#4 /home/***/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(889): do_action()
#5 /home/***/public_html/wp-content/plugins/woocommerce/includes/class-wc-checkout.php(1172): WC_Checkout->validate_checkout()
#6 /home/***/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(478): WC_Checkout->process_checkout()
#7 /home/***/public_html/wp-includes/class-wp-hook.php(307): WC_AJAX::checkout()
#8 /home/***/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#9 /home/***/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#10 /home/***/public_html/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(93): do_action()
#11 /home/***/public_html/wp-includes/class-wp-hook.php(307): WC_AJAX::do_wc_ajax()
#12 /home/***/public_html/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#13 /home/***/public_html/wp-includes/plugin.php(476): WP_Hook->do_action()
#14 /home/***/public_html/wp-includes/template-loader.php(13): do_action()
#15 /home/***/public_html/wp-blog-header.php(19): require_once('...')
#16 /home/***/public_html/index.php(17): require('...')
#17 {main}
  thrown in /home/***/public_html/wp-content/plugins/itella-shipping/admin/class-itella-shipping-method.php on
2022-09-26 08:45:49.712060 [NOTICE] [162979] [172.71.95.8:38242:HTTP2-1#***] [STDERR] line 1258

**Comment by rudolfgusta** [comment]
Seems, it was fixed already. Could you send update info to the plugin catalogue in Wordpress aswell and update links on Itella pages? Thanks.
